<?php

namespace App\Controller;

use Silex\WebTestCase;

/**
 * Test class for BookmarkController.
 * Generated by PHPUnit on 2012-12-21 at 10:06:45.
 */
class BookmarkControllerTest extends WebTestCase {

    function provider() {
        return array(
            array(
                array(
                    array("title" => "yahoo.com", "description" =>
                        "yahoo's website", "url" => "http://yahoo.fr","private"=>1,
                        "tags" => array("yahoo", "advertising", "life style")),
                    array("title" => "google.com", "description" =>
                        "google search engine", "url" => "http://google.com","private"=>0,
                        "tags" => array("google", "search", "popular", "advertising")),
                ),
                array(
                    "username" => "superman", "email" => "superman@yahoo.fr", "password" => "password"
                ),
                array("HTTP_Content-Type" => "application/json"),
            ),
        );
    }

    /**
     * @covers App\Controller\BookmarkController::create
     * @dataProvider provider
     */
    public function testCreate($bookmarks, $user, $headers) {
        // Remove the following lines when you implement this test.
        $client = $this->createClient();
        $client->request("POST", "/json/register", array(), array(), $headers, json_encode($user));
        //print_r($client->getResponse()->getContent());
        $client->request("POST", "/json/bookmark", array(), array(), $headers, json_encode($bookmarks[0]));
        $client->request("POST", "/json/bookmark", array(), array(), $headers, json_encode($bookmarks[1]));
        $response = $client->getResponse();
        $json = json_decode($response->getContent());
        print_r($client->getResponse()->getContent());
        $this->assertEquals($json->status, "ok");
    }

    /**
     * @covers App\Controller\BookmarkController::delete
     * @todo Implement testDelete().
     */
    public function testDelete() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    public function createApplication() {
        return createApplication();
    }

}

?>
