<?php
namespace MarkMe;

use Doctrine\ORM\EntityManager;
use Silex\WebTestCase;


/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1-7-gef8c3c6 on 2014-08-10 at 17:04:13.

 */
class AppTest extends WebTestCase

{


    /**
     * Creates the application.
     *
     * @return \MarkMe\App
     */
    public function createApplication()
    {
        return \Bootstrap::createApplication();
    }

    function testConstructor()
    {
        $this->assertInstanceOf('\Silex\Application', $this->app);
    }


    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.

     */

    public function setUp()

    {

        parent::setUp();

    }


    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.

     */

    public function tearDown()

    {
        parent::tearDown();
    }


    /**
     * @covers MarkMe\App::getTwig
     */

    public function testGetTwig()

    {
        $this->assertInstanceOf('\Twig_Environment', $this->app->getTwig());
    }


    /**
     * @covers MarkMe\App::getEntityManager
     */

    public function testGetEntityManager()

    {

        $this->assertInstanceOf('\Doctrine\ORM\EntityManager', $this->app->getEntityManager());

    }


    /**
     * @covers MarkMe\App::getSerializer
     */

    public function testGetSerializer()

    {

        $this->assertInstanceOf('\Symfony\Component\Serializer\Serializer', $this->app->getSerializer());

    }

}

